"""Generate docs/mcp-tool-catalog.md from the live MCP tool definitions plus real example calls.

python scripts/generate_tool_catalog.py
"""

from __future__ import annotations

import asyncio
import json
import logging
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
for p in ("", "apps/alarm-api-simulator", "mcp-servers/alarm-management"):
    sys.path.insert(0, str(ROOT / p))
os.environ.setdefault("ALARM_SIM_ANCHOR_TIME", "2026-09-30T00:00:00Z")
logging.disable(logging.CRITICAL)

import httpx  # noqa: E402

from alarm_api_sim.config import SimulatorSettings  # noqa: E402
from alarm_api_sim.main import create_app  # noqa: E402
from alarm_mcp.config import McpServerSettings  # noqa: E402
from alarm_mcp.server import create_server  # noqa: E402

W = {"start_time": "2026-07-02T00:00:00Z", "end_time": "2026-09-30T00:00:00Z"}

DETAILS = {
    "search_assets": ("GET /assets/search", {"query": "Boiler Feed Pump 101", "limit": 3}),
    "get_asset_metadata": ("GET /assets/{asset_id}/metadata", {"asset_id": "BFP-101"}),
    "get_alarms": ("GET /alarms (page/page_size; optional multi-page fetch)", {"asset_ids": ["BFP-102"], "status": "active"}),
    "get_alarm_details": ("GET /alarms/{alarm_id}", {"alarm_id": "ALM-000612"}),
    "summarize_alarms": (
        "POST /alarms/summary",
        {
            "asset_ids": ["BFP-101"],
            **W,
            "severities": ["high", "critical"],
            "group_by": ["alarm_name"],
            "kpis": ["alarm_count", "recurring_rate", "avg_ack_delay"],
        },
    ),
    "get_alarm_trends": ("POST /alarms/trends", {"asset_ids": ["BFP-101"], **W, "bucket": "weekly"}),
    "correlate_alarms": ("POST /alarms/correlation", {"asset_ids": ["BFP-101"], **W}),
    "analyze_alarm_floods": (
        "POST /alarms/flood-analysis",
        {"unit": "Unit 2", "start_time": "2026-05-01T00:00:00Z", "end_time": "2026-07-01T00:00:00Z"},
    ),
    "find_rationalization_candidates": ("POST /alarms/rationalization-candidates", {"site": "NorthPlant", "unit": "Unit 1", **W}),
    "score_alarm_priority": ("POST /alarms/priority-score", {"alarm_id": "ALM-000612"}),
    "get_operator_recommendations": ("POST /recommendations/operator-actions", {"alarm_id": "ALM-000617"}),
    "calculate_alarm_kpi": (
        "POST /calculation-code/generate -> POST /calculation-code/execute",
        {"calculation_type": "nuisance_alarm_score", "unit": "Unit 4", **W},
    ),
    "list_kpi_definitions": ("GET /analytics/kpi-definitions", {}),
}


def _shorten(value, depth=0):
    if isinstance(value, dict):
        return {k: _shorten(v, depth + 1) for k, v in list(value.items())[:14]}
    if isinstance(value, list):
        return [_shorten(v, depth + 1) for v in value[:2]] + (["..."] if len(value) > 2 else [])
    if isinstance(value, str) and len(value) > 160:
        return value[:160] + "..."
    return value


def _schema_table(schema: dict) -> str:
    props, required = schema.get("properties", {}), set(schema.get("required", []))
    if not props:
        return "_no parameters_"
    rows = ["| Parameter | Type | Required | Constraints / default | Description |", "|---|---|---|---|---|"]
    for name, p in props.items():
        kind = p.get("type") or " \\| ".join(str(a.get("type", a.get("$ref", "?")).split("/")[-1]) for a in p.get("anyOf", []))
        if p.get("items", {}).get("enum") or p.get("enum"):
            kind += f" enum {p.get('enum') or p['items']['enum']}"
        if isinstance(p.get("items"), dict) and "anyOf" not in p and p["items"].get("type"):
            kind = f"array[{p['items']['type']}]" + (f" enum {p['items']['enum']}" if p["items"].get("enum") else "")
        cons = ", ".join(
            f"{k}={p[k]}" for k in ("minimum", "maximum", "minLength", "maxLength", "maxItems", "minItems", "pattern", "format") if k in p
        )
        if "default" in p:
            cons = (cons + ", " if cons else "") + f"default={json.dumps(p['default'])}"
        rows.append(f"| `{name}` | {kind} | {'yes' if name in required else 'no'} | {cons} | {p.get('description', '')} |")
    return "\n".join(rows)


async def main() -> None:
    sim = create_app(SimulatorSettings())
    mcp = create_server(McpServerSettings(), api_transport=httpx.ASGITransport(app=sim))
    tools = await mcp.list_tools()
    md = [
        "# MCP tool catalog: `alarm-management` server",
        "",
        "_Generated by `python scripts/generate_tool_catalog.py` from the live tool definitions; example responses are real "
        "calls against the simulator (shortened)._",
        "",
        "## Common behaviour (all tools)",
        "",
        "| Aspect | Behaviour |",
        "|---|---|",
        "| Transport | Streamable HTTP at `http://<host>:9000/mcp` (stateless, JSON responses) or stdio (`python -m alarm_mcp --transport stdio`). |",
        "| Client authentication | `Authorization: Bearer $MCP_AUTH_TOKEN` required on `/mcp` (401 otherwise). `/health` is public. |",
        "| Upstream authentication | The server calls the Alarm API with `Authorization: Bearer $ALARM_API_TOKEN`. That token never leaves the server and is redacted from logs. |",
        "| Trace metadata | Client headers `x-trace-id` / `x-conversation-id` are forwarded as `trace_id` / `x-trace-id`, `x-client-id: alarm-mcp-server` and `x-metadata-tag: mcp-tool:<tool>;conversation:<id>`. A trace id is generated when absent. Every result carries `meta.trace_id`. |",
        "| Input validation | JSON-schema from typed signatures (types, enums, min/max, id pattern `^[A-Za-z0-9][A-Za-z0-9_.:-]{0,63}$`) plus semantic checks (start < end, max 400-day range, scope required). |",
        "| Output validation | Upstream payloads are validated against the output schema. A mismatch returns `UPSTREAM_CONTRACT_ERROR`. |",
        "| Timeout / retry | Per API call `ALARM_API_TIMEOUT_S` (default 10 s). Retries `ALARM_API_MAX_RETRIES` (default 2) on 429/502/503/504, timeouts and connection errors, with exponential backoff and jitter, honouring `Retry-After`. Retries are reported in `meta.api_calls[].retries`. |",
        '| Errors | Tool errors (`isError: true`) carry JSON `{"error": {code, message, status_code, retryable, attempts, trace_id, tool, endpoint, details}}`. Codes: `INVALID_ARGUMENT`, `NOT_FOUND`, `UNAUTHORIZED`, `RATE_LIMITED`, `UPSTREAM_UNAVAILABLE`, `UPSTREAM_TIMEOUT`, `UPSTREAM_CONTRACT_ERROR`. |',
        "| Annotations | All tools are `readOnlyHint: true`, `idempotentHint: true`, `destructiveHint: false`. There are no write operations. |",
        "",
        "## Tools",
        "",
        "| Tool | Underlying API operation |",
        "|---|---|",
        *[f"| [`{t.name}`](#{t.name.replace('_', '_')}) | `{DETAILS[t.name][0]}` |" for t in tools],
        "",
    ]
    for t in tools:
        endpoint, example = DETAILS[t.name]
        _content, result = await mcp.call_tool(t.name, example)
        md += [
            f"### `{t.name}`",
            "",
            f"**Purpose:** {t.description}",
            "",
            f"**Underlying operation:** `{endpoint}`",
            "",
            "**Input schema**",
            "",
            _schema_table(t.inputSchema),
            "",
            "<details><summary>Output schema (JSON Schema)</summary>",
            "",
            "```json",
            json.dumps(t.outputSchema, indent=1)[:6000],
            "```",
            "</details>",
            "",
            "**Example invocation**",
            "",
            "```json",
            json.dumps({"name": t.name, "arguments": example}, indent=2),
            "```",
            "",
            "**Example response (structured content, shortened)**",
            "",
            "```json",
            json.dumps(_shorten(result), indent=2, default=str)[:3500],
            "```",
            "",
        ]
    # error examples
    md += ["## Error examples", ""]
    for name, args in (
        ("get_asset_metadata", {"asset_id": "NOPE-1"}),
        ("get_alarms", {}),
        ("get_alarms", {"site": "X", "page_size": 1000}),
    ):
        try:
            await mcp.call_tool(name, args)
        except Exception as exc:
            md += [f"`{name}({json.dumps(args)})` →", "", "```text", str(exc)[:600], "```", ""]
    (ROOT / "docs" / "mcp-tool-catalog.md").write_text("\n".join(md), encoding="utf-8")
    print("wrote docs/mcp-tool-catalog.md")


if __name__ == "__main__":
    asyncio.run(main())
